package com.atlassian.dfcheck.core;

import java.io.File;
import java.util.Map;
import java.util.Set;

/**
 * A Differential check plugin that parses a plugin report and generates violations.
 */
public interface DfPlugin
{
    /**
     * @param pluginReport the report file generated by the plugin
     * @return a map of Source->Violation(s), based on the pluginReport.
     */
    Map<String, Set<Violation>> parse(File pluginReport);

    /**
     * @return the unique id of the plugin
     */
    String getPluginId();
}
